const express = require('express');
const userController = require('../controllers/userController');
const router = express.Router();
router.get('/',userController.user_index);
// router.get('/signup',userController.user_signup_get); // not needed
router.post('/',userController.user_signup_post);
router.get('/signin',userController.user_signin_get);
router.post('/signin',userController.user_signin_post);
router.get('/aboutus',userController.user_aboutus);
router.get('/aboutdevelopers',userController.user_aboutdevelopers);
router.get('/feedback',userController.user_feedback);
//router.get('/browser',userController.user_browser);
// router.get('/menu',userController.user_menu);
router.get('/home',userController.user_home);
router.get('/signin',userController.user_buy);
router.get('/addtocart',userController.user_addtocart);
router.get('/browser/viewallcomputer',userController.user_browser_viewall_computer);
router.get('/browser/viewallcivil',userController.user_browser_viewall_civil);
router.get('/browser/viewallmechanical',userController.user_browser_viewall_mechanical);
router.get('/browser/viewallelectronics',userController.user_browser_viewall_electronics);
router.get('/browser/viewallarchitecture',userController.user_browser_viewall_architecture);
router.get('/browser/:bookid',userController.user_browser_bookid);
router.get('/browser/:bookid/addtocart', userController.user_browser_bookid_addtocart_get);
//router.post('/browser/:bookid/addtocart', userController.user_browser_bookid_addtocart_post);
router.get('/mycart',userController.user_mycart);
router.post('/mycart',userController.user_mycart_orderpost);
router.get('/continueshopping',userController.user_continueshopping);
router.get('/:bookid/deleteacart',userController.user_deleteacart);
router.get('/order',userController.user_order);
router.get('/payment',userController.user_payment);
router.get('/download/:bookid',userController.user_download);
router.post('/feedback',userController.user_feedback_post);
router.get('/signout',userController.user_signout);
module.exports = router;
